sinaptik-ai/pandas-ai

- .pylintrc
- examples/data/sample_dataframe.py
- examples/from_dataframe.py
- examples/with_privacy_enforced.py
- pandasai/__init__.py
- pandasai/llm/base.py
- tests/test_pandasai.py
A couple of Changes:
1. Changed the signature of giving the prompt to LLM. Have asked it to return the Python code surrounded by "startCode" and "endCode". Found out by experimenting that the LLM is good at giving the output in this format and it becomes easy to extract the required code.
2. Added Error Correcting Framework With Max Retry of 3.
> Error Correcting Framework

- pandasai/__init__.py
> Fix conversational answer function

- pandasai/__init__.py
- tests/test_pandasai.py
> interpret json when llm returns json code

- README.md
- pandasai/__init__.py
- pandasai/helpers/anonymizer.py
- tests/test_anonymizer.py
- tests/test_pandasai.py
The main goal of this PR is to anonymize a few data (like email, phone numbers and credit cards) and shuffle the non-sensitive data. 
The reason behind it is that we're sending a data frame head to a remote LLM (like OpenAI GPT) and we want to be sure that the info cannot be used by anyone in an unwanted way.
> Anonymized data frame head

- tests/test_pandasai.py
This PR closes #26.
I didn't add any structural modifications like inserting fixtures. I'll let this to @Lorenzobattistela.
The only modification here was the replacement of the built-in unittest framework with pytest.
> feat: changed from built-in unittest to pytest framework

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
Enables users to add bug report with the minimal code they ran. 
Enables users to propose new feature request
Add PR template to link requests and issues and again reminding contributors to check mark all the pre-commit tests were run and additional tests were added
> Add: Issues & PR template

- CONTRIBUTING.md
- README.md
Things I did in the PR:
- Add extra steps to check the linting and testing before submitting the PR.
- Mark TODO: Contributing Guidelines as completed.
- Mark poetry as  `poetry`  to be similar to  `pylint` and  `pytest` in the CONTRIBUTING.md
> Fix contributing guildelines

- tests/test_pandasai.py
This code refactors `tests/test_pandasai.py` to use fixtures instead of multiple `setup()` calls.
> Using pytest fixtures instead of multiple function calls

- pandasai/__init__.py
Replaces manual capture of output with the nice function [capture_stdout](https://docs.python.org/3/library/contextlib.html#contextlib.redirect_stdout)  from contextlib
> refactor: use contextlib.redirect_stdout to capture the output

- CONTRIBUTING.md
> docs: added pre-commit to contributing.md

- .pre-commit-config.yaml
> fix: removed fixed python version in pre-commit

- examples/from_csv.py
- examples/from_dataframe.py
- examples/show_chart.py
- examples/with_privacy_enforced.py
- pandasai/llm/azure_openai.py
- pandasai/llm/base.py
- pandasai/llm/openai.py
- tests/llms/test_azure_openai.py
- tests/llms/test_openai.py
> isort marks local module as third party on import: fix unresolved import warning

- README.md
- pandasai/__init__.py
Hello @gventuri,
this minor PR introduces the simple functionality of running `PandasAI` with the functional operator, e.g.
```py
...
pandas_ai = PandasAI(llm, conversational=False)
result = pandasi(df, prompt)
```
`.run()` is however kept to guarantee retrocompatibilty.
> Allow running with __call__

- .gitignore
- pandasai/llm/base.py
- pandasai/llm/google_palm.py
- poetry.lock
- pyproject.toml
- tests/llms/test_google_palm.py
This PR aims to add support for Google Palm API.
> Feat: Add Support for Google Palm

- pyproject.toml
> fix: added entrypoint for cli access

- pandasai/llm/base.py
- tests/llms/test_base_hf.py
> fix(hf): wrong concatenation of prompt and suffix

- README.md
- docs/pai_cli.md
@gventuri adding these instructions would help to build & access the CLI tool. 
P.S. also refer to the attached PR
> docs: added cli access instructions

- pandasai/__init__.py
> fixed documentation

- pandasai/__init__.py
- pandasai/helpers/from_excel.py
- pandasai/helpers/save_chart.py
chore: fix typehints
fix: only create save_chart directory if there are calls to plt.show()
> chore: add save_charts documentation and format docs

- pandasai/__init__.py
- pandasai/constants.py
> add libs to whitelist

- pandasai/helpers/save_chart.py
The old [PR](https://github.com/gventuri/pandas-ai/pull/214) is closed
> fix: save chart path on unix

- pandasai/helpers/cache.py
> fix: fix cache tests

- pandasai/helpers/cache.py
Move cache file save directory to separate cache folder
Use glob to identify and remove all files related to the Cache instance
> fix: update cache.destroy() to remove all files

- pandasai/__init__.py
- pandasai/helpers/save_chart.py
- tests/helpers/test_save_chart.py
- tests/test_pandasai.py
Use a UUID to generate unique folders for each run of PandasAI to save charts to.
Add the UUID as a prompt id attribute to PandasAI, and open up with an interface in `last_prompt_id()`.
This allows projects built on top of PandasAI to easily retrieve charts generated.
> feat: unique chart folder names

- pandasai/helpers/anonymizer.py
- tests/helpers/test_anonymizer.py
- Closes #209 
- Tests added and passed.
- All code check passed.
> 🐛 Add pd eval to cell value to correct bool evaluation

- README.md
- docs/getting-started.md
Playing around with Google PaLM, I run into an exception due to the missing dependency (I forgot we made it optional😄). I realized we never provided instructions on how to install it "since the beginning".
> Optional installs instructions

- .gitignore
- pandasai/__init__.py
> chore: refactor log method to use logging module

- pandasai/llm/azure_openai.py
- tests/llms/test_azure_openai.py
> fix(azure-openai): drop deprecated Deployment API

- docs/shortcuts.md
- pandasai/helpers/shortcuts.py
**Summary:**
This pull request introduces a new function called `boxplot` to the existing codebase. The `boxplot` function is designed to draw a box-and-whisker plot, showcasing distributions with respect to categories. It supports various input options, including the ability to specify the column(s) of interest and the grouping variable(s).
**Function Signature:**
```python
def boxplot(self, df: pd.DataFrame, col: str | list[str] | None = None, by: str | list[str] | None = None, style: str | None = None):
```
**Changes Made:**
- Added a new function `boxplot` to the codebase.
- The function accepts a pandas DataFrame `df` as the primary data source.
- Introduced the `col` parameter, allowing users to specify a single column or a list of columns to be used for the box plot. The parameter …
> add .boxplot() shortcut

- pandasai/llm/langchain.py
this allows ChatModels to be called as well!
> fix langchain integration

- pandasai/llm/base.py
#340 
Fixes No code response for HF models
Made changes in pandasai/llm/base.by in 
call function of HuggingFaceLLM class
> Fixed "No Code Response for HF Models"

- pandasai/__init__.py
Add logging a message and a traceback when some error occurs during executing a code in `run_code()` method of `PandasAI` class.
> refactor: logging when code execution fails (#363)

- pandasai/helpers/anonymizer.py
Made some changes in anonymizer.py to handle edge case , when data has only one row.
> Fixed Fails for DataFrame of One Item

- docs/cache.md
> docs: Update cache parameter in cache.md 

- examples/from_csv_vertexai.py
- examples/from_dataframe_azure.py
- examples/save_chart.py
- pandasai/prompts/correct_error_prompt.py
- pandasai/prompts/generate_python_code.py
- pandasai/prompts/multiple_dataframes.py
- setup.py
- tests/helpers/test_openai_info.py
- tests/llms/test_azure_openai.py
- tests/llms/test_openai.py
- tests/prompts/test_correct_error_prompt.py
- tests/prompts/test_generate_python_code_prompt.py
- tests/prompts/test_multiple_dataframes_prompt.py
- tests/test_pandasai.py
> fix: removed extra "today" from prompts + liniting

- docs/callbacks.md
- pandasai/__init__.py
- pandasai/callbacks/__init__.py
- pandasai/callbacks/base.py
- pandasai/callbacks/file.py
- tests/test_pandasai.py
```py
from pandasai import PandasAI
from pandasai.llm.openai import OpenAI
from pandasai.callbacks import FileCallBack
cb = FileCallBack(filename="generated.py")
llm = OpenAI()
df = ... # <-- define your df here
question = "..." # <-- your question here!
pandas_ai = PandasAI(llm, callback=cb)
response = pandas_ai(df, question)
```
> feat(callbacks): add file callback

- pandasai/__init__.py
-  closes #379 
- All [code checks passed](https://github.com/gventuri/pandas-ai#contributing).
> fix : remove unnecessary pompt argument

- pandasai/agent/base.py
- pandasai/llm/__init__.py
- pandasai/llm/langchain.py
> fix(agent): langchain LLM instantiation

- pandasai/llm/base.py
- pandasai/llm/google_gemini.py
- pandasai/llm/google_palm.py
- pandasai/llm/google_vertexai.py
:warning:  I don't have a Google Cloud subscription nor an API key for Gemini. I've tested this mocking the call to Gemini. Make sure to try this out properly before merging.
[OT] :partying_face: Congrats on the 10k stars!
> fix(llm): Google Gemini signature and memory usage

- .github/workflows/ci.yml
> build: fix ci for windows

- pandasai/agent/base.py
- pandasai/connectors/polars.py
- pandasai/helpers/dataframe_serializer.py
- pandasai/helpers/file_importer.py
- pandasai/helpers/output_validator.py
- pandasai/prompts/direct_sql_prompt.py
- pandasai/responses/response_serializer.py
- tests/unit_tests/helpers/test_file_importer.py
- tests/unit_tests/test_file_importer.py
> fix(pandas): modin support broke from pandasai>=2.0

- docs/LLMs/llms.md
> docs(llm): support local LLMs compatible with OpenAI API

- docs/LLMs/llms.md
- pandasai/llm/local_llm.py
- tests/unit_tests/llms/test_local_llm.py
> feat(llm): add API key as param to local LLM

- pandasai/llm/google_gemini.py
> fix: AttributeError: 'GoogleGemini' object has no attribute 'google'

- poetry.lock
- pyproject.toml
> build: upgrade Modin and pandas versions

- pandasai/llm/base.py
- pandasai/llm/openai.py
> feat: openai support to modify openai's base url

- pandasai/agent/base.py
- tests/unit_tests/agent/test_agent.py
> fix: none type error in notebooks

- docs/getting-started.md
* (docs): missing comma in python snippet
* (docs): proofreading
___
> docs: minor updates in getting-started.md

- pandasai/vectorstores/bamboo_vectorstore.py
- tests/unit_tests/vectorstores/test_bamboo_vector_store.py
> fix(fetch_training_error): query without training data if fails to fetch

- pandasai/connectors/base.py
- pandasai/helpers/dataframe_serializer.py
- pandasai/prompts/templates/generate_python_code_with_sql.tmpl
- pandasai/schemas/df_config.py
- tests/unit_tests/pipelines/smart_datalake/test_prompt_generation.py
- tests/unit_tests/prompts/test_correct_error_prompt.py
- tests/unit_tests/prompts/test_generate_python_code_prompt.py
- tests/unit_tests/prompts/test_sql_prompt.py
Convert to yml if a field description is provided
> feat: default to csv serializer

- pandasai/schemas/df_config.py
- tests/unit_tests/schemas/test_df_config.py
This fixes the ongoing issue with #1054.
> fix: config llm None

- pandasai/pipelines/chat/code_execution.py
- pandasai/responses/response_serializer.py
- tests/unit_tests/responses/test_response_serializer.py
> feat: support series in response serializer

- Makefile
> ci/cd: Makefile auto put ## to help

- pandasai/helpers/output_validator.py
- tests/unit_tests/helpers/test_output_validator.py
> feat: add plotly support for output validators

- pandasai/pipelines/chat/code_execution.py
- pandasai/pipelines/chat/error_correction_pipeline/error_correction_pipeline.py
- pandasai/pipelines/chat/generate_chat_pipeline.py
> fix: pipeline to run new code and update last generated code

- examples/using_chainlit.py
- [N/A] Closes #xxxx (Replace xxxx with the GitHub issue number).
- [N/A] Tests added and passed if fixing a bug or adding a new feature.
Added file to examples/ that shows using chainlit as the conversational UI for PandasAI
> chore: chainlit example using_chanlit.py

- examples/using_chainlit.py
> fix: JSON not serializable fix in using_chainlit.py

- server/api/v1/__init__.py
- server/api/v1/datasets/datasets.py
- server/api/v1/workspace/__init__.py
- server/api/v1/workspace/workspace.py
- server/app/controllers/workspace.py
- server/app/repositories/workspace.py
- server/app/schemas/responses/users.py
- server/core/repository/base.py
> [PAN-802]: Get workspace user endpoint added

- server/api/v1/conversations/conversations.py
- server/app/controllers/conversation.py
- server/app/controllers/workspace.py
> [PAN-820]: archive conversation api added

- docs/library.mdx
- docs/platform.mdx
Fixed a minor typo in the docs.
> DOC: Few typos fixed

- pandasai/pipelines/chat/code_cleaning.py
- tests/unit_tests/pipelines/smart_datalake/test_code_cleaning.py
Change: add skills to the environment in `_extract_fix_dataframe_redeclarations` method.
Note: I didn't add any new test.
> fix: skill name is not defined

- server/Dockerfile
Thanks @johnfelipe for the solution https://github.com/Sinaptik-AI/pandas-ai/issues/1372#issuecomment-2373713960
> Fix server Dockerfile

- client/app/(ee)/settings/logs/page.tsx
- client/app/settings/datasets/[id]/page.tsx
- client/app/settings/datasets/page.tsx
- client/app/settings/page.tsx
- client/app/settings/workspaces/addspaces/page.tsx
- client/app/settings/workspaces/editspaces/page.tsx
- client/app/settings/workspaces/page.tsx
This pull request resolves an issue where running docker-compose failed due to a duplicate dynamic const definition in the code.
•	Removed/Updated the duplicate dynamic const to fix the build error.
> Fixed duplicate export dynamics when building client app

- server/Dockerfile
> Add /app to PYTHONPATH
