sinaptik-ai/pandas-ai

.pylintrc, pyproject.toml
This PR closes #68. 
The branch name in the `.pylintrc` file was `MASTER`, that's why the linting in tests was not ignored. 
And I took this opportunity to move the `.pylintrc` config to `pyproject.toml`.
=> move pylint config from `.pylintrc` file to `pyproject.toml`

.github/workflows/cd.yml, .github/workflows/ci.yml, README.md
=> feat: add auto pypi publish on new release

examples/from_csv.py, examples/from_dataframe.py, examples/show_chart.py, examples/with_privacy_enforced.py
This is just a left over from yesterday's PR. I replaced `run` with the functional operator in the README forgetting to do that in the examples.
=> Replace `run` with `__call__` in examples

.github/workflows/ci.yml, pandasai/llm/base.py, poetry.lock, pyproject.toml, tests/llms/test_google_palm.py
Hi @gventuri, 
this PR aims at addressing #53. 
- google-palm becomes an optional dep, installable via `poetry install --extras google` or `pip install pandasai[google]` or `poetry install --all-extras`. Reference: [poetry documentation](https://python-poetry.org/docs/pyproject/#extras)
- the test workflow installs also the optional dependencies to appropriately run all the tests. A possible alternative would be to instead use `pytest.importskip`, which is the approach adopted in langchain. This would skip the tests of the optional deps. I let you decide what you prefer :)
=> chore(deps): make google-palm optional dep

.pre-commit-config.yaml, CONTRIBUTING.md, pandasai/__init__.py, pandasai/helpers/notebook.py, pandasai/llm/base.py, pandasai/llm/fake.py, pandasai/llm/openai.py
Update CONTRIBUTING.md for running tests: pytest -> poetry run pytest
Fix typehints
For many, tests might fail necessarily when they run `pytest`,  `poetry run pytest` will ensure the right environment and dependencies are used and will avoid version mismatches.
Updated the command in CONTRIBUTING.md and pre-commit-config.
Fix some type hints mismatch after this [commit](https://github.com/gventuri/pandas-ai/commit/6862977169a3416ead856870d595eb21bb6a57d0)
=> Update pre-commit-config entry for pytest check

CONTRIBUTING.md
Running `poetry install` does not install all dependencies required in tests. 
Update instructions in CONTRIBUTING.md to include `--all-extras` flag. 
Closes #182
=> docs: update dependency install instructions

pandasai/helpers/save_chart.py
The issue is due to the file separator because on windows, the separator is a backslash `\`, while on Unix-based systems it is a forward slash `/`
=> fix: save charts dir path on unix

pandasai/__init__.py, pandasai/constants.py, tests/test_pandasai.py
`matplotlib` is added to the environment passed to `exec()`, it should not also be imported in the run code.
Remove `matplotlib` from `WHITELISTED_LIBRARIES`, so imports are removed from the generated code.
Add ENVIRONMENT_DEFAULTS variable to consolidate logic.
=> fix: remove matplotlib from whitelisted libraries

poetry.lock, pyproject.toml
LLMs may not be trained on more recent versions of `pandas`, and could generate code that is deprecated since 2.0.0
=> fix: revert pandas dependency to 1.5.3

pandasai/llm/base.py, tests/helpers/test_anonymizer.py, tests/helpers/test_cache.py, tests/llms/test_base_hf.py, tests/llms/test_base_llm.py, tests/llms/test_google_palm.py, tests/llms/test_openai.py, tests/llms/test_starcoder.py, tests/prompts/test_correct_error_prompt.py, tests/prompts/test_correct_multiples_prompt.py, tests/prompts/test_generate_python_code_prompt.py, tests/prompts/test_generate_response_prompt.py, tests/prompts/test_multiple_dataframes_prompt.py, tests/test_pandasai.py
- Refactor tests closer to the interface.
- Remove unused imports and other linting.
- Resolve type hint errors.
- Add test for reading cache from file.
Motivation: https://softwareengineering.stackexchange.com/questions/380287/why-is-unit-testing-private-methods-considered-as-bad-practice
=> test: remove private method assertions

pandasai/__init__.py, pandasai/helpers/save_chart.py, tests/helpers/test_save_chart.py
Return the chart save directory to the user using the logging framework instead of adding a print statement to the run code. When `verbose=False`, print directory to the console.
=> feat: move chart dir output to log

pandasai/helpers/_optional.py
The package manager enforces the versions of non-optional dependencies.
=> fix: remove non-optional dependencies from VERSIONS

pandasai/__init__.py
Fix type hint for `data_frame` parameter across methods of `PandasAI` class. According to [L275 of `__init__.py`](https://github.com/gventuri/pandas-ai/blob/main/pandasai/__init__.py#L275) the parameter can be a list of `DataFrame` objects.
=> fix: type hinting error

examples/from_dataframe_azure.py, pandasai/llm/azure_openai.py, tests/llms/test_azure_openai.py
Hi @gventuri, this PR adds an example showcasing how to use `AzureOpenAI` and refactors a bit the content of the Azure backend (mainly forcing the user to specify an `api_version` for proper usage)
=> chore(examples): add azure openai example

docs/building_docs.md, docs/llms.md, pandasai/llm/azure_openai.py, pandasai/llm/base.py, pandasai/llm/openai.py, tests/llms/test_azure_openai.py, tests/llms/test_openai.py
@gventuri  This PR aims at supporting explicit proxy in OpenAI LLMs.
=> feat(openai): support explicit proxy

tests/llms/test_langchain_llm.py
Minor fix:
Update signature for `__call__()` method of `FakeOpenAI` mock according to it's base class.
Although it seems like it has no effect for now, because [the only place i found of usage](https://github.com/gventuri/pandas-ai/blob/main/pandasai/llm/langchain.py#L18) for that is just passing only `prompt` parameter. But i think it'd be better to keep method's original signature anyway, this basically seems to remove violation of Liskov Abstraction principle.
=> tests: fix signature of a method in a fixture

pandasai/__init__.py, pandasai/helpers/save_chart.py
=> Fix code newline character issue introduced by astor.to_source

tests/test_pandasai.py
This patch is for contributors who are developing on Windows platform. Some tests were failing because of [`\r\n` instead of `\n`](https://www.cs.toronto.edu/~krueger/csc209h/tut/line-endings.html#:~:text=Text%20files%20created%20on%20DOS,(%22%5Cn%22).), the problem described in issue https://github.com/gventuri/pandas-ai/issues/347
___
Add [checking for platform](https://docs.python.org/3/library/sys.html#sys.platform) in some test cases and replacing `\r\n` with `\n` if the platform's name starts with `"win"`.
* add compatibility for win platforms in [`test_run_with_privacy_enforcement()`](https://github.com/gventuri/pandas-ai/blob/main/tests/test_pandasai.py#L197)
* add compatibility for win platforms in [`test_run_without_privacy_enforcement()`](https://github.com/gventuri/pandas-ai/bl …
=> tests: fix failing tests for win platform (#347)

.github/workflows/ci.yml
Given the experience coming from this [issue](https://github.com/gventuri/pandas-ai/issues/347), this PR aims at making the CI pipeline run on windows and macOS as well.
=> ci: run on windows and macos latest

docs/llms.md, pandasai/helpers/openai_info.py, pandasai/llm/base.py, tests/helpers/test_openai_info.py
Hi @gventuri,
this PR aims at supporting token usage count and cost tracking for OpenAI llms, adapting and simplifying langchain's implementation. 
Supposed usage:
```py
"""Example of using PandasAI with a Pandas DataFrame"""
import pandas as pd
from data.sample_dataframe import dataframe
from pandasai import PandasAI
from pandasai.llm.openai import OpenAI
from pandasai.helpers.openai_info import get_openai_callback
df = pd.DataFrame(dataframe)
llm = OpenAI()
pandas_ai = PandasAI(llm, enable_cache=False, conversational=True)
with get_openai_callback() as cb:
response = pandas_ai(df, "Calculate the sum of the gdp of north american countries")
print(response)
print(cb)
#	Prompt Tokens: 210
#	Completion Tokens: 165
```
Of course it also works with `AzureOpenAI`.
**Missing tests for now.**
=> feat(openai): add token usage and cost tracking callback

pandasai/__init__.py, tests/test_pandasai.py
This commit adds possibility to specify log level when calling `.log()` method from `PandasAI` class.
The `INFO` level remains to be default value, so it won't affect any part of existing code.
___
* feat: update `log()` method of `PandasAI`, add passing log level as a parameter
* feat: add saving log level in logs container
* feat: update typing accordingly
* tests: update test for saving logs, add checking of logging for different levels
=> feat: passing log level in `log()` method (#368)

pandasai/helpers/.cph/.anonymizer.py_82b914668ef0feac8c997d3a8f661bb2.prob, pandasai/helpers/anonymizer.py, pandasai/llm/base.py, tests/helpers/test_anonymizer.py
Fixed issue for multi-line code output when using HF model. Made changes in hugging face class of base.py inside LLM.
Fixed Capitalized Integer dtypes Failure
=> fixed issue for multi-line code for HF model and fixed Capitalized Integer dtypes Failure

docs/llms.md
Hi @gventuri, 
this PR fixes the llms documentation and specifically the naming of the api key parameter, which is called `api_key` for all of them.
I make the most of this PR to ask if you prefer to have "langchain-like" naming instead, i.e. `<provider>_api_<type>` (`huggingface_api_token`, `openai_api_type` etc.). If it is the case, we gotta change the parameters naming in the classes API. I can do that appending a commit to this PR. 
Otherwise, this is ready for review :)
=> docs: fix api_key param

pandasai/__init__.py
There are some cosmetic things merged in https://github.com/gventuri/pandas-ai/pull/392 that i guess would rather be refactored.
___
Mutual default parameter in the method's signature. Mutual default arguments (like `values: Dict = {}`) can cause unpredictable behavior.
```
>>> def foobar(bar=[]):
...     bar.append('test')
...     print(f'List {bar} with ID {id(bar)}')
>>>
>>>
>>> foobar()
List ['test'] with ID 140147921265664
>>> foobar()
List ['test', 'test'] with ID 140147921265664  # as you see function hasn't create an empty list during second call, instead picked already existed
```
I've shown example with a list, but it's works same for dict, etc. (basically any mutual object).
See:
https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument …
=> refactor: update `_get_prompt()` in `PandasAI`

pandasai/__init__.py, tests/test_pandasai.py
=> fix: bypass the security check with prompt injection (#399)

pandasai/__init__.py, pandasai/prompts/multiple_dataframes.py, tests/prompts/test_multiple_dataframes_prompt.py
Fixing bug which sends the dataframe head when anonymize_df=True in the multidataframe case.
Also fixing bug which tells the model that dataframe has 0 rows when enforce_privacy = True in the multidataframe case.
- [ x ] closes #418
=> Fixing multidataframe bugs when enforcing privacy

pandasai/__init__.py, pandasai/llm/__init__.py, pandasai/middlewares/__init__.py, tests/test_pandasai.py
Fixed the _is_df_override method to check for all targets in an assignment statement, ensuring that no potential DataFrame overwrites are missed.
=> improved on _is_df_overwrite method to check all targets

pandasai/__init__.py, tests/test_pandasai.py
This PR should resolve the problem with environment described in issue #400.
For now i've just added `matplotlib.pyplot` as "plt" in `_get_environment()` method. The package is present in dependency list, code from the issue runs without failures, it must works OK.
However it's still unclear for me, should we add the rest of popular packages, such as `numpy` as "np" and so on? Although `PandasAI` already has [`import_dependency()`](https://github.com/gventuri/pandas-ai/blob/main/pandasai/helpers/_optional.py#L45) util-function, and this logic in theory must have to avoid this problem, this  couldn't work because of (regarding to [the issue](https://github.com/gventuri/pandas-ai/issues/400)) HuggingFace just had returned code using `plt` variable without import statement — just something …
=> fix: environment for executing code

mkdocs.yml
Add edit uri to solve the issue Link at main doc page is pointing to non-existent page #670
=> docs: add edit_uri in mkdocs.yml

pyproject.toml
Relaxing `sqlalchemy` requirements to allow usage of sqlalchemy 2.x.
=> chore: relaxing sqlalchemy versions to include 2.x.

pandasai/agent/callbacks.py, pandasai/pipelines/chat/code_execution.py, pandasai/pipelines/chat/generate_chat_pipeline.py, tests/unit_tests/agent/test_agent.py
Repeat of #992 (can't be reopened) and targets the same issue as #1007 .
=> fix: set Agent.last_code_executed correctly

pandasai/helpers/code_manager.py
Add attribute check to avoid "AttributeError: 'Call' object has no attribute 'id' or "AttributeError: 'Subscript' object has no attribute 'id'"
=> fix: add attribute check to avoid "AttributeError: 'Call' object has no attribute 'id'

pandasai/helpers/code_manager.py, tests/unit_tests/test_codemanager.py
Targets the same issue as #1013 , but adds a test to cover where `value.func.value` has type `ast.Subscript` or `ast.Call`, instead of type `ast.Name` as expected.
=> fix: access value.func.value.id after checking AST node

pandasai/helpers/memory.py, pandasai/llm/base.py, pandasai/llm/local_llm.py, tests/unit_tests/llms/test_local_llm.py
Similar to [CrewAI's approach](https://docs.crewai.com/how-to/LLM-Connections/#openai-compatible-api-endpoints) to supporting local LLMs.
```python
from pandasai.llm.local_llm import LocalLLM
```
Ollama's compatibility is experimental (see [docs](https://github.com/ollama/ollama/blob/main/docs/openai.md)).
```python
llm = LocalLLM(model="ollama-model", api_base="http://localhost:11434/v1")
```
```python
llm = LocalLLM(model="", api_base="http://localhost:1234/v1")
```
=> feat(llm): support local LLMs compatible with OpenAI API

pandasai/agent/base.py, tests/unit_tests/agent/test_agent.py
=> fix: wrap LangChain LLMs correctly

pandasai/helpers/code_manager.py, pandasai/helpers/output_validator.py, tests/unit_tests/test_codemanager.py
=> fix: code manager to handle data not defined error

pandasai/ee/vectorstores/__init__.py, pandasai/ee/vectorstores/qdrant.py, poetry.lock, pyproject.toml, tests/unit_tests/vectorstores/test_qdrant.py
This PR adds support for [Qdrant](https://qdrant.tech/) to be used as a vector store.
=> feat: Qdrant vector store support

pandasai/connectors/sql.py, tests/unit_tests/connectors/test_sqlite.py
function for sqlite connector
Closes #1067
=> fix: sqlite connector override base equals

pandasai/pipelines/chat/code_cleaning.py
=> fix: code cleaning using wrong context

pandasai/pipelines/chat/code_execution.py
This is to avoid cases where the generated code uses df, which gives the following error: NameError: name 'df' is not defined
=> fix: add df to environment for the good measure

pandasai/llm/bedrock_claude.py
Adding Claude's opus model (anthropic.claude-3-opus-20240229-v1:0) to BedrockClaude & updating the attributes comment.
Opus is currently available in the us-west-2 region.
=> adding claudes opus model to  bedrock &  updating attributes comment

pandasai/llm/base.py, tests/unit_tests/llms/test_base_llm.py
* Add tests to cover more cases for `_extract_code` and `_is_python_code`
Motivation:
Using a dataframe with a large number of columns, the `LLM()._execute_code` method would fail when asking how many rows there are in the dataframe. The failure would be because the LLM wasn't using triple back ticks to surround the code.
If the LLM produces correct python code, but for some reason does not
preface it with \```, the `LLM()._extract_code` method fails with
NoCodeFoundError.
In this change we first check if the separator is included in the response and we take only the part that is in-between. Then we clean the code from `python/py` statements.
Then we check if it's valid code. This check should pass otherwise executing the code will fail, and it's better to raise an error earlier than …
```
=> fix:Introduce `_is_python_code` check into `_extract_code`

pandasai/helpers/openai_info.py
Adding gpt-4o to the list of GPT-4 output.
=> Update openai_info.py:  adding gpt-4o to the list of GPT-4 output

pandasai/connectors/__init__.py, pandasai/connectors/sql.py, pyproject.toml, tests/unit_tests/connectors/test_sql.py
=> Fix (cx_Oracle.DatabaseError) ORA-00904

docs/llms.mdx
Description fix proposal.
I found on the docs the link to have the free api key for the Bamboo LLM. So I thought this might be outdated and you might want to make the api key available publicly now. Feel free to refuse it or to fix it if necessary.
=> docs: llms.mdx had outdated info about bambooLLM api key

client/app/settings/datasets/AddNewCard.tsx, client/app/settings/datasets/page.tsx, client/app/settings/workspaces/[id]/WorkspaceCard.tsx, client/app/settings/workspaces/[id]/page.tsx, client/app/settings/workspaces/addspaces/AddSpaceCard.tsx, client/app/settings/workspaces/addspaces/loading.tsx, client/app/settings/workspaces/addspaces/page.tsx, client/app/settings/workspaces/editspaces/EditSpaceCard.tsx, client/app/settings/workspaces/editspaces/loading.tsx, client/app/settings/workspaces/editspaces/page.tsx, client/app/settings/workspaces/loading.tsx, client/app/settings/workspaces/page.tsx, client/app/settings/workspaces/space-interface.ts, client/components/SettingsLayout/LeftBar.tsx, client/hooks/useSpaces.tsx, client/lib/actions.ts, client/services/spaces.ts, server/api/v1/workspace/workspace.py, server/app/controllers/workspace.py, server/app/repositories/workspace.py, server/app/schemas/requests/workspace.py
=> [PAN-868]: workspaces added

client/Providers/AppProvider.tsx, client/components/LogsTable/index.tsx
=> import path fixed

pandasai/llm/azure_openai.py
Azure OpenAI api key (when not using active directory authentication) was not being passed to the underlying openai object.
Oneline fix...
=> Fix Azure OpenAI LLM backend

pandasai/smart_dataframe/__init__.py
I ran into `RecursionError: maximum recursion depth exceeded` when using SmartDataframe and found the issue is caused by a call to `__getattr__` trying to access `_core` which does not exist, but it calls `__getattr__ ` repeatedly.
There may be something I don't understand in the code here, and that this has a reason to exist, but this solved my problems.
To reproduce the problem, create a smart data frame with e.g.
```python
import os
import pandas as pd
from pandasai import SmartDataframe
sales_by_country = pd.DataFrame({
"country": ["United States", "United Kingdom", "France", "Germany", "Italy", "Spain", "Canada", "Australia", "Japan", "China"],
"revenue": [5000, 3200, 2900, 4100, 2300, 2100, 2500, 2600, 4500, 7000]
})
os.environ["PANDASAI_API_KEY"] = "<insert_key>"
df = …
```
=> Removed _core property on SmartDataframe that causes maximum recursion depth exceeded

pandasai/pipelines/chat/code_cleaning.py
=> fix bug in malicious code scan
